src/config/urls.py
from django.contrib import admin
from django.urls import path, include

from nucleo import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('saludar/', views.saludar ),
    path('saluda_etiqueta/', views.saludar_etiqueta),
    path('', include('nucleo.urls')),
    path('dado/', views.tirar_dado),
    path('notas/', views.notas),
    path('producto/', include('producto.urls')),
]

src/nucleo/urls.py
from django.urls import path

from nucleo import views

app_name = 'nucleo'

urlpatterns = [
    path('', views.index, name='index'),
]

src/producto/urls.py
from django.urls import path

from producto import views

app_name = 'producto'

urlpatterns = [
    path('lista/', views.producto_list, name='lista'),
]

src/nucleo/models.py
from django.db import models

# Create your models here.

src/producto/models.py
from django.db import models

# Create your models here.
class Categoria(models.Model):
    nombre = models.CharField(max_length=250, unique=True)
    descripcion = models.TextField(null=True, blank=True)

    def __str__(self):
        return f'{self.nombre} ( {self.descripcion})'

src/nucleo/views.py
from django.http import     HttpResponse
from django.shortcuts import render
# Create your views here.


def saludar (request):
    return HttpResponse('Hola desde Django!')
def saludar_etiqueta(request):

    return HttpResponse('<h1> hola desde la app</h1>')

def index(request):
    return render(request, 'nucleo/index.html', {'titulo': 'Proyecto : django'})

def tirar_dado(request):
    from datetime import datetime
    from random import randint  
    
    tiro_de_dado = randint(1,6)

    if tiro_de_dado == 6:
        mensaje = f'has tirado {tiro_de_dado} y has ganado'
    else:
        mensaje = f'has tirado {tiro_de_dado} y has perdido'
    datos = {
        'titulo': 'Tirar dado',
        'mensaje': mensaje,
        'fecha': datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    }
    return render(request, 'nucleo/dado.html', datos)

def notas(request):
    mis_notas = [21, 12, 3, 4, 5, 6, 7, 8, 9, 10]
    return render(request, 'nucleo/notas.html', {'notas': mis_notas})

src/producto/views.py
from django.shortcuts import render
from . import models

# Create your views here.
def producto_list(request):
    productos = models.Categoria.objects.all()
    return render(request, 'producto/producto_list.html', {'productos': productos})

src/nucleo/templates/nucleo/dado.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {{ titulo }}</title>
</head>
<body>
    <h1> {{ titulo }}</h1>
    <p>{{ mensaje }}</p>
    <p>{{ fecha }}</p>
</body>
</html>

src/nucleo/templates/nucleo/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
</head>
<body>
    <h1> {{ titulo }}</h1>
    <h2>framework de python</h2>
    <p>Hay Miles de herramientas, para que querer inventar la rueda!!   </p>
    <a href="{% url 'producto:lista' %}">Lista de Productos</a>
</body>
</html>

src/nucleo/templates/nucleo/notas.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        .note {
            display: inline-block;
            margin: 10px;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            color: #333;
            background-color: #f5f5f5;
        }
        .note.red {
            background-color: #fdd;
        }
        .note.green {
            background-color: #dfd;
        }
        .note.blue {
            background-color: #ddf5fd;
        }
    </style>
</head>
<body>
    <h1>Notas</h1>
    {% for nota in notas %}
    <p class="note {% if nota < 5 %}red{% elif nota >= 5 and nota < 8 %}green{% else %}blue{% endif %}">{{ nota }}</p>
    {% endfor %}
</body>
</html>